# Generated by Django 4.2.30 on 2026-09-10 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SundaySchoolCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('age_group', models.CharField(choices=[('toddlers', 'Toddlers (2-4)'), ('primary', 'Primary (5-9)'), ('juniors', 'Juniors (10-13)'), ('teens', 'Teens (14-18)'), ('all', 'All Ages')], default='primary', max_length=20)),
                ('lesson_date', models.DateField(blank=True, null=True)),
                ('scripture', models.CharField(blank=True, max_length=200)),
                ('memory_verse', models.CharField(blank=True, max_length=300)),
                ('lesson', models.TextField(help_text='The teaching material for the Sunday school teacher')),
                ('activities', models.TextField(blank=True, help_text='Suggested activities, songs or crafts for the children')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_school_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sunday school courses',
                'ordering': ['-lesson_date', '-created_at'],
            },
        ),
    ]
