# Generated by Django 6.1.1 on 2026-09-28 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sundayschoolcourse',
            name='audio',
            field=models.FileField(blank=True, help_text='Audio file (e.g. MP3, M4A, OGG) shared with this course.', null=True, upload_to='sunday_school/'),
        ),
        migrations.AddField(
            model_name='sundayschoolcourse',
            name='pdf_attachment',
            field=models.FileField(blank=True, help_text='PDF document shared with this course.', null=True, upload_to='sunday_school/'),
        ),
        migrations.AddField(
            model_name='sundayschoolcourse',
            name='video',
            field=models.FileField(blank=True, help_text='Video file (e.g. MP4, WebM) shared with this course.', null=True, upload_to='sunday_school/'),
        ),
        migrations.AddField(
            model_name='sundayschoolcourse',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video link (YouTube, Vimeo, Facebook, Dailymotion, etc.). Plays inline on the site.'),
        ),
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('attachment', models.FileField(blank=True, help_text='Optional PDF attachment. Only visible to administrators.', null=True, upload_to='sunday_school/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sunday_school.sundayschoolcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunday_school_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
