# Generated by Django 6.1.1 on 2026-09-28 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_school', '0002_sundayschoolcourse_audio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sundayschoolcourse',
            name='enable_registration',
            field=models.BooleanField(default=False, help_text='Show a "Join the Class" button and let members enrol.'),
        ),
        migrations.AddField(
            model_name='sundayschoolcourse',
            name='max_students',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum number of students. Leave blank for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='sundayschoolcourse',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='If checked, the teacher must approve each join request.'),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='sunday_school.sundayschoolcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunday_school_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('course', 'student')},
            },
        ),
    ]
