# Generated by Django 6.1.1 on 2026-09-28 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('sunday_school', '0003_sundayschoolcourse_enable_registration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='child',
            field=models.ForeignKey(blank=True, help_text='Used when a child is on the class.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='children.child'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Used when an adult (e.g. a parent or teacher) is on the class.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_school_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('course', 'student'), name='unique_course_student'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', False)), fields=('course', 'child'), name='unique_course_child'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('child__isnull', False), ('student__isnull', False), _connector='OR'), name='course_enrollment_has_student_or_child'),
        ),
    ]
