# Generated by Django 4.2.30 on 2026-09-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('speaker', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('bible_verse', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sermon_notes', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sermons/audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='sermons/video/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='sermons/pdf/')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
