# Generated by Django 4.2.30 on 2026-09-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='series',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sermon',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='category',
            field=models.CharField(blank=True, choices=[('sunday', 'Sunday Service'), ('midweek', 'Midweek'), ('evangelism', 'Evangelism'), ('teaching', 'Teaching'), ('youth', 'Youth'), ('special', 'Special Service')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='speaker',
            field=models.CharField(help_text='Who gave the sermon', max_length=200),
        ),
    ]
