# Generated by Django 4.2.30 on 2026-09-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0002_sermon_series_sermon_youtube_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='category',
            field=models.CharField(blank=True, choices=[('sunday', 'Sunday Service'), ('midweek', 'Midweek'), ('evangelism', 'Evangelism'), ('teaching', 'Teaching'), ('devotion', 'Devotion'), ('youth', 'Youth'), ('special', 'Special Service')], max_length=100),
        ),
    ]
