# Generated by Django 6.1.1 on 2026-09-28 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giving',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='givings', to='members.member'),
        ),
        migrations.AlterField(
            model_name='giving',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank'), ('card', 'Card'), ('online', 'Online'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='OnlineGiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('giving_category', models.CharField(choices=[('tithe', 'Tithe'), ('offering', 'Offering'), ('donation', 'Donation'), ('building_fund', 'Building Fund'), ('missions', 'Missions'), ('special_contribution', 'Special Contribution'), ('other', 'Other')], max_length=30)),
                ('frequency', models.CharField(choices=[('one_time', 'One-time'), ('monthly', 'Monthly'), ('annual', 'Annually')], default='one_time', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('reference_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('voided', 'Voided')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('giving', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_record', to='giving.giving')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_givings', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
