# Generated by Django 4.2.30 on 2026-09-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='church/'),
        ),
    ]
