# Generated by Django 4.2.30 on 2026-09-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_churchsetting_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsetting',
            name='cta_image',
            field=models.ImageField(blank=True, help_text='Call to action section image', null=True, upload_to='church/'),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='events_image',
            field=models.ImageField(blank=True, help_text='Events section image', null=True, upload_to='church/'),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Homepage hero background (1920x1080 recommended)', null=True, upload_to='church/'),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='sermons_image',
            field=models.ImageField(blank=True, help_text='Sermons section image', null=True, upload_to='church/'),
        ),
    ]
