# Generated by Django 4.2.30 on 2026-09-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_churchsetting_cta_image_churchsetting_events_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('pastor', 'Pastor'), ('secretary', 'Secretary'), ('finance_officer', 'Finance Officer'), ('ministry_leader', 'Ministry Leader'), ('group_leader', 'Group Leader'), ('media', 'Media'), ('usher', 'Usher'), ('worship_team', 'Praise & Worship Team'), ('member', 'Member')], max_length=20)),
                ('module', models.CharField(choices=[('members', 'Members'), ('families', 'Families'), ('visitors', 'Visitors'), ('services', 'Services'), ('attendance', 'Attendance'), ('ministries', 'Ministries'), ('groups', 'Groups'), ('children', 'Children'), ('events', 'Events'), ('sermons', 'Sermons'), ('songs', 'Praise & Worship'), ('bible_study', 'Bible Study'), ('sunday_school', 'Sunday School'), ('announcements', 'Announcements'), ('finance', 'Finance'), ('giving', 'Giving'), ('assets', 'Assets'), ('facilities', 'Facilities'), ('reports', 'Reports'), ('users', 'User Management'), ('settings', 'Settings')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Role module permissions',
                'unique_together': {('role', 'module')},
            },
        ),
    ]
