# Generated by Django 6.1.1 on 2026-09-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsetting',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Homepage sermon player audio (MP3 recommended, keep under ~10MB)', null=True, upload_to='church/audio/'),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='audio_speaker',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='audio_title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
