# Generated by Django 6.1.1 on 2026-09-24 11:51

from django.db import migrations, models

from core.about_defaults import about_defaults


def backfill_about_content(apps, schema_editor):
    ChurchSetting = apps.get_model('core', 'ChurchSetting')
    defaults = about_defaults()
    for obj in ChurchSetting.objects.all():
        changed = False
        for field, value in defaults.items():
            if not getattr(obj, field):
                setattr(obj, field, value)
                changed = True
        if changed:
            obj.save(update_fields=list(defaults.keys()))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_churchsetting_audio_file_churchsetting_audio_speaker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsetting',
            name='about_call',
            field=models.TextField(blank=True, help_text='"Our Call" card text on the About page.', null=True),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='about_divine_promise',
            field=models.TextField(blank=True, help_text='"Our Divine Promise" card text on the About page.', null=True),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='about_history_body',
            field=models.TextField(blank=True, help_text='About page history. Separate paragraphs with a blank line.', null=True),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='about_history_image',
            field=models.ImageField(blank=True, help_text='About page image (recommended 1280x575 or wider).', null=True, upload_to='church/'),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='about_history_intro',
            field=models.TextField(blank=True, help_text='About page intro paragraph.', null=True),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='about_milestones',
            field=models.TextField(blank=True, help_text='Key Milestones. One per line, format: Date | Description', null=True),
        ),
        migrations.RunPython(backfill_about_content, migrations.RunPython.noop),
    ]
