# Generated by Django 6.1.1 on 2026-10-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_churchsetting_featured_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsetting',
            name='footer_color',
            field=models.CharField(blank=True, help_text='Solid footer background colour. Leave blank to use the primary colour.', max_length=7),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='navbar_color',
            field=models.CharField(blank=True, help_text='Solid navbar background colour. Leave blank to use the primary colour.', max_length=7),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='section_color',
            field=models.CharField(blank=True, help_text='Solid background colour for section header bands. Leave blank to use the primary colour.', max_length=7),
        ),
    ]
