# Generated by Django 6.1.1 on 2026-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_churchsetting_footer_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsetting',
            name='impact_1_label',
            field=models.CharField(blank=True, default='Families Fed Monthly', max_length=60),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='impact_1_note',
            field=models.CharField(blank=True, default='Through our community food program', max_length=140),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='impact_1_value',
            field=models.CharField(blank=True, default='500+', max_length=16),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='impact_2_label',
            field=models.CharField(blank=True, default='Students Sponsored', max_length=60),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='impact_2_note',
            field=models.CharField(blank=True, default='Receiving education through our scholarship fund', max_length=140),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='impact_2_value',
            field=models.CharField(blank=True, default='120', max_length=16),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='impact_3_label',
            field=models.CharField(blank=True, default='Churches Planted', max_length=60),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='impact_3_note',
            field=models.CharField(blank=True, default='New congregations established across the region', max_length=140),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='impact_3_value',
            field=models.CharField(blank=True, default='12', max_length=16),
        ),
    ]
