# Generated by Django 6.1.1 on 2026-10-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_churchsetting_impact_1_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodulepermission',
            name='module',
            field=models.CharField(choices=[('members', 'Members'), ('families', 'Families'), ('visitors', 'Visitors'), ('services', 'Services'), ('attendance', 'Attendance'), ('ministries', 'Ministries'), ('groups', 'Groups'), ('children', 'Children'), ('events', 'Events'), ('sermons', 'Sermons'), ('songs', 'Praise & Worship'), ('bible_study', 'Bible Study'), ('sunday_school', 'Sunday School'), ('announcements', 'Announcements'), ('finance', 'Finance'), ('giving', 'Giving'), ('assets', 'Assets'), ('facilities', 'Facilities'), ('impact', 'Impact & Outreach'), ('reports', 'Reports'), ('users', 'User Management'), ('settings', 'Settings')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rolemodulepermission',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('pastor', 'Pastor'), ('secretary', 'Secretary'), ('finance_officer', 'Finance Officer'), ('ministry_leader', 'Ministry Leader'), ('group_leader', 'Group Leader'), ('media', 'Media'), ('usher', 'Usher'), ('worship_team', 'Praise & Worship Team'), ('sponsor', 'Sponsor'), ('member', 'Member')], max_length=20),
        ),
    ]
