# Generated by Django 6.1.1 on 2026-10-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundedperson',
            name='household_size',
            field=models.PositiveIntegerField(blank=True, help_text='Number of people in the household.', null=True),
        ),
        migrations.AddField(
            model_name='fundedperson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='impact/'),
        ),
        migrations.AddField(
            model_name='fundedperson',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Approved for the public Give page. Untick to remove it again.'),
        ),
        migrations.AddField(
            model_name='fundedperson',
            name='location',
            field=models.CharField(blank=True, help_text='Estate, village or ward.', max_length=200),
        ),
        migrations.AddField(
            model_name='fundedperson',
            name='story',
            field=models.TextField(blank=True, help_text='Life detail of the family. Only shown publicly after approval.'),
        ),
    ]
