# Generated by Django 6.1.1 on 2026-10-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0002_fundedperson_household_size_fundedperson_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundedperson',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text="Person's age in years.", null=True),
        ),
        migrations.AddField(
            model_name='fundedperson',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact number for follow-up.', max_length=30),
        ),
    ]
