# Generated by Django 6.1.1 on 2026-10-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0004_fundedperson_record_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundedperson',
            name='age',
        ),
        migrations.AddField(
            model_name='fundedperson',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Person's date of birth.", null=True),
        ),
    ]
