# Generated by Django 6.1.1 on 2026-10-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0005_remove_fundedperson_age_fundedperson_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundedperson',
            name='assigned_deacon',
            field=models.CharField(blank=True, help_text='Deacon or deaconess assigned for follow-up, prayer and discipleship.', max_length=150),
        ),
    ]
