# Generated by Django 4.2.30 on 2026-09-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleStudyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('bible_verse', models.CharField(max_length=200)),
                ('study_date', models.DateField()),
                ('teacher', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('key_points', models.TextField(blank=True)),
                ('prayer_points', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-study_date'],
            },
        ),
    ]
