# Generated by Django 4.2.30 on 2026-09-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblestudynote',
            name='discussion_questions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='biblestudynote',
            name='series',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
