# Generated by Django 6.1.1 on 2026-09-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_study', '0003_biblestudycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblestudynote',
            name='audio',
            field=models.FileField(blank=True, help_text='Audio file (e.g. MP3, M4A, OGG) shared with this study.', null=True, upload_to='bible_study/'),
        ),
        migrations.AddField(
            model_name='biblestudynote',
            name='pdf_attachment',
            field=models.FileField(blank=True, help_text='PDF document shared with this study.', null=True, upload_to='bible_study/'),
        ),
        migrations.AddField(
            model_name='biblestudynote',
            name='video',
            field=models.FileField(blank=True, help_text='Video file (e.g. MP4, WebM) shared with this study.', null=True, upload_to='bible_study/'),
        ),
    ]
