# Generated by Django 6.1.1 on 2026-09-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_study', '0004_biblestudynote_audio_biblestudynote_pdf_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblestudynote',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video link (YouTube, Vimeo, Facebook, etc.). YouTube videos play inline.'),
        ),
    ]
