# Generated by Django 6.1.1 on 2026-09-28 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_study', '0005_biblestudynote_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='biblestudynote',
            name='enable_registration',
            field=models.BooleanField(default=False, help_text='Show a "Join the Class" button and let members enrol.'),
        ),
        migrations.AddField(
            model_name='biblestudynote',
            name='max_students',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum number of students. Leave blank for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='biblestudynote',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='If checked, the teacher must approve each join request.'),
        ),
        migrations.AlterField(
            model_name='biblestudynote',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video link (YouTube, Vimeo, Facebook, Dailymotion, etc.). Plays inline on the site.'),
        ),
        migrations.CreateModel(
            name='BibleStudyEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_study_enrollments', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='bible_study.biblestudynote')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('study', 'student')},
            },
        ),
    ]
