# Generated by Django 4.2.30 on 2026-09-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('pastor', 'Pastor'), ('secretary', 'Secretary'), ('finance_officer', 'Finance Officer'), ('ministry_leader', 'Ministry Leader'), ('group_leader', 'Group Leader'), ('media', 'Media'), ('usher', 'Usher'), ('worship_team', 'Praise & Worship Team'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
