# Generated by Django 6.1.1 on 2026-09-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_group',
            field=models.CharField(blank=True, choices=[('', 'Not set'), ('toddlers', 'Toddlers (2-4)'), ('primary', 'Primary (5-9)'), ('juniors', 'Juniors (10-13)'), ('teens', 'Teens (14-18)')], default='', help_text='Used to target Sunday School classes by age group.', max_length=20),
        ),
    ]
