# Generated by Django 6.1.1 on 2026-10-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('pastor', 'Pastor'), ('secretary', 'Secretary'), ('finance_officer', 'Finance Officer'), ('ministry_leader', 'Ministry Leader'), ('group_leader', 'Group Leader'), ('media', 'Media'), ('usher', 'Usher'), ('worship_team', 'Praise & Worship Team'), ('sponsor', 'Sponsor'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
