# Generated by Django 4.2.30 on 2026-09-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('hymn', 'Hymn'), ('worship', 'Worship Song'), ('praise', 'Praise Song'), ('gospel', 'Gospel Song'), ('contemporary', 'Contemporary'), ('chorus', 'Chorus')], default='hymn', max_length=20)),
                ('lyrics', models.TextField()),
                ('author', models.CharField(blank=True, max_length=200)),
                ('key', models.CharField(blank=True, max_length=10)),
                ('tempo', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
