# Generated by Django 4.2.30 on 2026-09-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='scripture',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.CharField(choices=[('praise', 'Praise'), ('worship', 'Worship'), ('hymn', 'Hymn'), ('gospel', 'Gospel'), ('chorus', 'Chorus'), ('contemporary', 'Contemporary')], default='praise', max_length=20),
        ),
    ]
