# Generated by Django 4.2.30 on 2026-09-07 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('member', 'Member'), ('visitor', 'Visitor'), ('child', 'Child')], default='member', max_length=20)),
                ('visitor_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.member')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('service', 'member')},
            },
        ),
    ]
